[package]
name = "grocks"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = "0.23.0"
tokio = { version = "1.44.2", features = ["full"]}
jsonrpsee = { version = "0.24.9", features = ["server"]}